### ISSUE TITLE
installation testing mac

### ISSUE THREAD

**Issue by fipoucat** [pmlmodelling/nctoolkit#8]
I installed the toolkit but have many errors at plot stage.

>>> ds = nc.open_data("/Users/sarr/Downloads/test.nc")
>>> ds.plot()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/nctoolkit/plot.py", line 2, in plot
    from ncplot import view
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/ncplot/__init__.py", line 1, in <module>
    from ncplot.plot import view
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/ncplot/plot.py", line 4, in <module>
    from cartopy import crs
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/cartopy/__init__.py", line 104, in <module>
    import cartopy.crs
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/cartopy/crs.py", line 19, in <module>
    import shapely.geometry as sgeom
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/shapely/geometry/__init__.py", line 4, in <module>
    from .base import CAP_STYLE, JOIN_STYLE
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/shapely/geometry/base.py", line 18, in <module>
    from shapely.coords import CoordinateSequence
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/shapely/coords.py", line 8, in <module>
    from shapely.geos import lgeos
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/shapely/geos.py", line 112, in <module>
    _lgeos = CDLL(os.path.join(sys.prefix, 'lib', 'libgeos_c.dylib'))
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/ctypes/__init__.py", line 373, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: dlopen(/Library/Frameworks/Python.framework/Versions/3.8/lib/libgeos_c.dylib, 6): image not found

What could be causing this? and what to do?

Thanks

**Comment by r4ecology** [comment]
This appears to be an issue with the cartopy installation, not nctoolkit per se.

The smoothest way to nctoolkit is using conda, as that will sort out system dependencies. But if you are using pip, you should probably install cartopy's system dependencies here: https://scitools.org.uk/cartopy/docs/latest/installing.html. It looks like GEOS is the problem.

**Comment by fipoucat** [comment]
I am trying to reinstall using conda and will update you.

**Comment by fipoucat** [comment]
Stil having the same errors after install using conda instead of pip?

**Comment by r4ecology** [comment]
What is the error message when using conda?

**Comment by fipoucat** [comment]
(/Applications/anaconda3) macasarr:~ sarr$ python
Python 3.8.2 (v3.8.2:7b3ab5921f, Feb 24 2020, 17:52:18)
[Clang 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import nctoolkit as nc
nctoolkit is using Climate Data Operators version 1.9.10
>>> ds = nc.open_data("/Users/sarr/Downloads/test.nc")
>>> ds.plot()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File
"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/nctoolkit/plot.py",
line 2, in plot
    from ncplot import view
  File
"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/ncplot/__init__.py",
line 1, in <module>
    from ncplot.plot import view
  File
"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/ncplot/plot.py",
line 4, in <module>
    from cartopy import crs
  File
"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/cartopy/__init__.py",
line 104, in <module>
    import cartopy.crs
  File
"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/cartopy/crs.py",
line 19, in <module>
    import shapely.geometry as sgeom
  File
"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/shapely/geometry/__init__.py",
line 4, in <module>
    from .base import CAP_STYLE, JOIN_STYLE
  File
"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/shapely/geometry/base.py",
line 18, in <module>
    from shapely.coords import CoordinateSequence
  File
"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/shapely/coords.py",
line 8, in <module>
    from shapely.geos import lgeos
  File
"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/shapely/geos.py",
line 112, in <module>
    _lgeos = CDLL(os.path.join(sys.prefix, 'lib', 'libgeos_c.dylib'))
  File
"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/ctypes/__init__.py",
line 373, in __init__
    self._handle = _dlopen(self._name, mode)
OSError:
dlopen(/Library/Frameworks/Python.framework/Versions/3.8/lib/libgeos_c.dylib,
6): image not found

**Comment by r4ecology** [comment]
I'm not a Mac user. But is that actually the conda version of Python?

**Comment by fipoucat** [comment]
I'll check this more closely, because I am having the same error message
when I try to import cartopy

**Comment by r4ecology** [comment]
I'm closing the issue, as it relates purely to cartopy.
